// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8kAvRq3j59AR5Nis4OnoIEjkH_wbhb-w',
    appId: '1:384705339602:web:4edebdde6f850e64184d0b',
    messagingSenderId: '384705339602',
    projectId: 'kik-movies',
    authDomain: 'kik-movies.firebaseapp.com',
    storageBucket: 'kik-movies.firebasestorage.app',
    measurementId: 'G-00XZFH42LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGYcKG3Y4mwjFuLedyzJo8qFZjs7s0-FQ',
    appId: '1:384705339602:android:bd0a742b6f32b091184d0b',
    messagingSenderId: '384705339602',
    projectId: 'kik-movies',
    storageBucket: 'kik-movies.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQuzdqPaBaifdkpOy7DQpT-fQhIg3c6VU',
    appId: '1:384705339602:ios:2ab746cab446be77184d0b',
    messagingSenderId: '384705339602',
    projectId: 'kik-movies',
    storageBucket: 'kik-movies.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQuzdqPaBaifdkpOy7DQpT-fQhIg3c6VU',
    appId: '1:384705339602:ios:2ab746cab446be77184d0b',
    messagingSenderId: '384705339602',
    projectId: 'kik-movies',
    storageBucket: 'kik-movies.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8kAvRq3j59AR5Nis4OnoIEjkH_wbhb-w',
    appId: '1:384705339602:web:d216bf70a33a8324184d0b',
    messagingSenderId: '384705339602',
    projectId: 'kik-movies',
    authDomain: 'kik-movies.firebaseapp.com',
    storageBucket: 'kik-movies.firebasestorage.app',
    measurementId: 'G-45K443LRXC',
  );
}
